# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cursor_zb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Zb@123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.bing.framework: DEBUG