# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/bing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.bing.framework: WARN